/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ParticleTracking_Analyse_Movie */

#ifndef _Included_ParticleTracking_Analyse_Movie
#define _Included_ParticleTracking_Analyse_Movie
#ifdef __cplusplus
extern "C" {
#endif
#undef ParticleTracking_Analyse_Movie_VERSION
#define ParticleTracking_Analyse_Movie_VERSION 4L
#undef ParticleTracking_Analyse_Movie_TRACK_EXT
#define ParticleTracking_Analyse_Movie_TRACK_EXT 1.0f
#undef ParticleTracking_Analyse_Movie_TRACK_OFFSET
#define ParticleTracking_Analyse_Movie_TRACK_OFFSET 0.75f
/*
 * Class:     ParticleTracking_Analyse_Movie
 * Method:    cudaGaussFitter
 * Signature: (Ljava/lang/String;Ljava/lang/String;FFFFII)Z
 */
JNIEXPORT jboolean JNICALL Java_ParticleTracking_Analyse_1Movie_cudaGaussFitter
  (JNIEnv *, jobject, jstring, jstring, jfloat, jfloat, jfloat, jfloat, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
