/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ParticleTracking_Timelapse_Analysis */

#ifndef _Included_ParticleTracking_Timelapse_Analysis
#define _Included_ParticleTracking_Timelapse_Analysis
#ifdef __cplusplus
extern "C" {
#endif
#undef ParticleTracking_Timelapse_Analysis_TRACK_OFFSET
#define ParticleTracking_Timelapse_Analysis_TRACK_OFFSET 1.0f
/*
 * Class:     ParticleTracking_Timelapse_Analysis
 * Method:    cudaGaussFitter
 * Signature: (Ljava/lang/String;Ljava/lang/String;FFFFII)Z
 */
JNIEXPORT jboolean JNICALL Java_ParticleTracking_Timelapse_1Analysis_cudaGaussFitter
  (JNIEnv *, jobject, jstring, jstring, jfloat, jfloat, jfloat, jfloat, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
