/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ParticleTracking_Timelapse_Analysis */

#ifndef _Included_ParticleTracking_Timelapse_Analysis
#define _Included_ParticleTracking_Timelapse_Analysis
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ParticleTracking_Timelapse_Analysis
 * Method:    cudaGaussFitter
 * Signature: (Ljava/lang/String;FFF)Z
 */
JNIEXPORT jboolean JNICALL Java_ParticleTracking_Timelapse_1Analysis_cudaGaussFitter
  (JNIEnv *, jobject, jstring, jfloat, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
