/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ParticleTracking_Analyse_ */

#ifndef _Included_ParticleTracking_Analyse_
#define _Included_ParticleTracking_Analyse_
#ifdef __cplusplus
extern "C" {
#endif
#undef ParticleTracking_Analyse__VERSION
#define ParticleTracking_Analyse__VERSION 4L
#undef ParticleTracking_Analyse__TRACK_EXT
#define ParticleTracking_Analyse__TRACK_EXT 1.0f
#undef ParticleTracking_Analyse__TRACK_OFFSET
#define ParticleTracking_Analyse__TRACK_OFFSET 0.75f
/*
 * Class:     ParticleTracking_Analyse_
 * Method:    cudaGaussFitter
 * Signature: (Ljava/lang/String;Ljava/lang/String;FFFFII)Z
 */
JNIEXPORT jboolean JNICALL Java_ParticleTracking_Analyse_1_cudaGaussFitter
  (JNIEnv *, jobject, jstring, jstring, jfloat, jfloat, jfloat, jfloat, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
